# Generated by Django 5.0.3 on 2024-03-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dep_discription',
            new_name='dep_description',
        ),
    ]
